# Generated by Django 4.2 on 2024-10-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_estoque', models.IntegerField()),
                ('preco_unidade', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
